apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend-service
    name: frontend-service
  name: frontend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-service
      name: frontend-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: frontend-service
        name: frontend-service
    spec:
      containers:
#      can be overwritten with "-set spec.template.spec.containers[0].image=image_url"
      - image: nimbleplatform/frontend-service:IMAGE_TAG
        imagePullPolicy: Always
        name: frontend-service
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 400m
            memory: 512Mi
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "k8s"
